name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ${{github.workspace}}/iz/gradlew
        shell: bash

      - name: Build with Gradle Wrapper
        working-directory: iz
        run: ./gradlew build -x test
        shell: bash

      - name: Run Tests
        working-directory: iz
        run: ./gradlew test
        shell: bash

      # 나머지 배포 단계는 동일하게 유지
