name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x iz/gradlew
        shell: bash

      - name: Build with Gradle
        working-directory: iz
        run: ./gradlew build -x test
        shell: bash

      - name: Run Tests
        working-directory: iz
        run: ./gradlew test
        shell: bash

      - name: Deploy to NCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          key: ${{ secrets.NCP_SSH_KEY }}
          source: "iz/build/libs/iz-0.0.1-SNAPSHOT.jar"
          target: "/opt/myapp/"
          strip_components: 2

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          key: ${{ secrets.NCP_SSH_KEY }}
          script: |
            cd /opt/myapp
            mv iz-0.0.1-SNAPSHOT.jar app.jar
            systemctl restart myapp
