name: Deploy to NCP
on:
  push:
    branches: [ main ]  # 또는 master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./iz
      
    - name: Build with Gradle
      run: |
        ./gradlew build --build-cache -x test
        echo "JAR files found:"
        find . -name "*.jar"
      working-directory: ./iz    
      
    - name: Deploy to NCP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_HOST_IP }}
        username: nbpmon
        key: ${{ secrets.NCP_PEM_KEY }}
        port: 22
        script: |
          cd /opt/izikgram
          pkill -f 'java -jar' || true
          sleep 5
          find . -name "*.jar" -type f -delete
          cp ${{ github.workspace }}/iz/build/libs/iz-0.0.1-SNAPSHOT.jar ./app.jar
          nohup java -jar app.jar > /dev/null 2>&1 &
          sleep 5
          if pgrep -f 'java -jar'; then
            echo "Application started successfully"
            exit 0
          else
            echo "Failed to start application"
            exit 1
          fi
