name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: iz

      - name: Run Tests
        run: ./gradlew test
        working-directory: iz

      - name: Debug build directory
        run: |
          echo "Build directory contents:"
          ls -R ${{ github.workspace }}/iz/build/libs

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to NCP
        run: |
          echo "Connected successfully"
          mkdir -p ~/app
          cd ~/app
          echo "Copying JAR file..."
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ github.workspace }}/iz/build/libs/iz-0.0.1-SNAPSHOT.jar root@223.130.150.215:/root/app/
          echo "Listing app directory:"
          ls -l
          echo "Stopping existing application..."
          pkill -f 'java -jar' || true
          echo "Starting new application..."
          nohup java -jar iz-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          echo "Application started"
