name: Deploy to NCP
on:
  push:
    branches: [ main ]  # 또는 master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.NCP_HOST_IP}}
          username: nbpnom
          key: ${{secrets.NCP_PEM_KEY}}
          port: 22
          script: |
            whoami
            cd /app/sara-frontend
            git pull origin main
            npm install --force
            npm run build
            nginx -s reload
