name: CI/CD with Gradle and Docker

on:
  push:
    branches:
      - kth  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./iz

    steps:
    # 코드 체크아웃
    - name: 소스 코드 체크아웃
      uses: actions/checkout@v4

    # JDK 설정
    - name: JDK 17 설정
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Gradle 캐시 설정 (빌드 속도 향상)
    - name: Gradle 캐시 설정
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    # Gradle 빌드
    - name: Gradle 빌드 및 테스트
      run: |
        chmod +x gradlew
        ./gradlew clean build -x test
      working-directory: ${{ env.working-directory }}

    # Docker Hub 로그인
    - name: Docker Hub 로그인
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Docker 이미지 빌드 및 푸시
    - name: Docker 이미지 빌드 및 푸시
      run: |
        docker build -t kokiyo1030/izikgram:${{ github.sha }} .
        docker push kokiyo1030/izikgram:${{ github.sha }}
      working-directory: ${{ env.working-directory }}

    # 서버에 Docker 이미지 배포
    - name: 서버에 Docker 배포
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # echo "✅ 서버 접근 성공!"
          # docker stop kokiyo1030/izikgram || true
          # docker rm kokiyo1030/izikgram || true
          # 최신 이미지 pull
          docker pull kokiyo1030/izikgram:${{ github.sha }}
          # 환경변수 설정 후 배포
          cd /root
          # docker run -d -p 8080:8080 --env-file .env --name izikgram kokiyo1030/izikgram:${{ github.sha }}
          # 최신 이미지로 컨테이너 재시작
          TAG=${{ github.sha }} docker compose down
          TAG=${{ github.sha }} docker compose up -d
